### ISSUE TITLE
Not possible to automate "hold" parameters

### ISSUE THREAD

**Issue by bartwronski** [MikeMorenoDSP/LIRA-8#1]
When trying to automate "hold" parameters in Ableton's clip, they get "reset" and not automated. Clicking on "re-enable automation" resets them to the current value, but again disables the automation. Ableton manuals suggest this being an issue with parameters handling / resets in plugins, but I'm not sure.

Repro steps:
1. Create automation in a clip for the hold parameters by drawing curves.
2. Start the clip.
3. Notice the hold values don't change and Ableton's "re-enable automation" button lights up.
4. When clicking it, current value of curve gets applied, but then automation disabled again.

**Comment by MikeMorenoDSP** [comment]
Fixed on this release:
[New "Quantize" parameter and fixed automation issue](https://github.com/MikeMorenoDSP/LIRA-8/tree/82421daf2f0446d00f0f21fdebb3984181a98054)
