### ISSUE TITLE
Plugin is not recognized in Ableton Live 11 & Macbook Pro M1 Max

### ISSUE THREAD

**Issue by frankbergere** [MikeMorenoDSP/LIRA-8#6]
1. Hi, I bought the plugin on https://mikemorenodsp.gumroad.com/l/lira-8 and it seems to be really good but I can not use it.

2. **Describe your environment**
    - Macbook Pro M1 Max
    - **OS**:  MacOS 12.2.1
    - **DAW**: Ableton Live 11 Suite
    - **Plugin**: VST3/AU - v1.0.8
    - **Audio**: headphones output

3. **Describe the problem or the feature request**
    a- I have copied the files LIRA-8.component and LIRA-8.vst3 in /Library/Audio/Plug-Ins/Components and /Library/Audio/Plug-Ins/VST3
    b- executed Terminal command line as specified here: https://www.reddit.com/r/MacOS/comments/ge4v0w/help_with_vst_plugins_from_an_unidentified/
    Terminal.txt in attachments
    c - Restart the Macbook and Rescan the Ableton Live plugins folder

THE PLUGIN IS STILL NOT RECOGNIZED. See video capture here : https://a.cl.ly/X6uEJ8R7
       
    d - Tried with https://github.com/MikeMorenoDSP/LIRA-8/releases/tag/v1.0.7, same issue
            
    > Feel free to provide your patches, your DAW project, screenshots and any document that could help.

[Terminal_export.txt](https://github.com/MikeMorenoDSP/LIRA-8/files/8219149/Terminal_export.txt)

Do you have any other recommandation or update ?

**Comment by MikeMorenoDSP** [comment]
Hello,
Please see my latest response on this discussion: #4 
You might need to turn off mac's gatekeeper.
